// 4 featured apps for the home-page carousel
// (a curated subset from the full list in ShopifyApps.jsx)

export const featuredApps = [
  {
    id: 'pagefly',
    name: 'PageFly Landing Page Builder',
    category: 'Page Builders',
    rating: '4.9',
    reviews: '9,000+',
    price: 'Free plan available',
    desc: 'Create highly responsive, stunning landing pages, product page templates, and homepages with an intuitive zero-code drag-and-drop builder.',
    link: 'https://apps.shopify.com/pagefly',
    benefit: 'Drag & Drop Builder',
    whyBest: 'Provides the most extensive free tier and customizable elements of any Shopify builder.',
    color: 'icon-blue',
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo: Email & SMS',
    category: 'Marketing',
    rating: '4.6',
    reviews: '1,800+',
    price: 'Free to install',
    desc: 'The gold standard e-commerce email marketing suite. Set up advanced customer segmentation, automated email/SMS flows, and rich data campaigns.',
    link: 'https://apps.shopify.com/klaviyo',
    benefit: 'Automated Ecom Flows',
    whyBest: 'Unmatched store data integration allows highly personalized automation and precise revenue tracking.',
    color: 'icon-orange',
  },
  {
    id: 'judge-me',
    name: 'Judge.me Product Reviews',
    category: 'Social Proof',
    rating: '5.0',
    reviews: '30,000+',
    price: 'Free plan available',
    desc: 'The most reviewed app on Shopify. Collect and display beautiful photo and video reviews to build shopper trust and boost conversion rates.',
    link: 'https://apps.shopify.com/judgeme',
    benefit: 'Photo & Video Reviews',
    whyBest: 'Highest review count on the entire Shopify App Store. Fully free core plan with no review limits.',
    color: 'icon-pink',
  },
  {
    id: 'recharge',
    name: 'Recharge Subscriptions',
    category: 'Subscriptions & Upsell',
    rating: '4.5',
    reviews: '1,600+',
    price: 'From $99/month',
    desc: 'Maximize customer lifetime value with a powerful subscription management platform. Handle complex billing, customer portals, and cancellation flows.',
    link: 'https://apps.shopify.com/subscription-payments',
    benefit: 'Recurring Revenue Engine',
    whyBest: 'The enterprise-grade standard for subscription commerce. Powers thousands of 7-figure DTC brands.',
    color: 'icon-purple',
  },
];
